Add conteúdo relacionado a Dead Space e água de esgoto
TucanoStation/tucano-station-14 pull request #7
Opened 2024-02-09 05:18 UTC by VictorJob

Lista de entidades adicionadas:
+Mob Necromorph Slayer e sua Carcaça
+Arma Plasma Cutter
+Hardsuit de Forças Especiais
+Tile/Objeto Água de Esgoto
+Áudio das respectivas entidades

Todas as entidades foram adicionadas na pasta Dead Station 14 que agora pode ser encontrada nas pastas /Resources/Prototypes, /Resources/Texture e /Resources/Audio. 

Essa pasta foi criado com o intuito de ser um fork próprio, porém a ideia não foi adiante na época, entretanto pretendo manter e adicionar conteúdo de Dead Space nela somente por organização. Gosto da Ideia disso parecer uma "DLC" e ter uma pasta somente pra isso combina.

![imagem_2024-02-09_020749071](https://github.com/TucanoStation/tucano-station-14/assets/117521143/eecc2035-007e-4171-b55d-06670e2a38a8)

2024-02-10 06:22 UTC, VictorJob commented
Acabei de descobrir que só pode criar um push request por vez, soda. 

Então, adicionei mais 2 commits a esse PR, um adicionando o Bananilson e os decalques da estação tucano e outro corrigindo o áudio do bananilson.


https://github.com/TucanoStation/tucano-station-14/assets/117521143/52b0e3ee-2732-46dd-afd9-3e024830e506

2024-02-11 16:58 UTC, joshepvodka requested changes
Os sprites do necromorph usam hueshifting demais e ficam mto claros e saturados, deixa as partes vermelhas dele mais escuras pra combinar um pouco melhor com o resto da arte do jogo.

2024-02-11 16:59 UTC, joshepvodka requested changes
Pra mim o plasmacutter também é muito azul e claro, deixa ele mais neutro.

2024-02-21 12:14 UTC, VictorJob commented
O vídeo foi gravado antes de fazer os ajustes no dano da arma, atualmente ela não está tão letal assim.

https://github.com/TucanoStation/tucano-station-14/assets/117521143/d8beec18-e264-427e-9f8e-b76b7bfb73ff

![image](https://github.com/TucanoStation/tucano-station-14/assets/117521143/d3d00c17-6a4d-4961-a8b1-0b95ec9f3af7)

![image](https://github.com/TucanoStation/tucano-station-14/assets/117521143/d09cfef7-d5aa-4dca-88c2-9d49ad9cdf0c)

2024-02-22 04:26 UTC, VictorJob commented
agora dá pra colocar o chapéu do hop no Ian
https://github.com/TucanoStation/tucano-station-14/assets/117521143/327b82ef-031c-4427-ad5d-2c440de01ee0

2024-02-23 04:13 UTC, merged